.\"     Title: nikto
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 2025-06-29
.\"    Manual: Vulnerability Scanner
.\"    Source: http://cirt.net/ 2.5.0
.\"
.TH "NIKTO" "1" "2025-06-29" "http://cirt\&.net/ 2\&.5" "Vulnerability Scanner"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
nikto \- Scan web server for known vulnerabilities
.SH "SYNOPSIS"
.HP 21
\fBnikto\fR [options...]
.SH "DESCRIPTION"
.PP
Nikto is an Open Source web server scanner which performs comprehensive tests against web servers for multiple items that are generally considered dangerous. It checks for dangerous files, outdated server software, and other problems.
.PP
Nikto is built on LibWhisker and can run on any platform which has a Perl environment\&. It supports SSL, proxies, host authentication, attack encoding and more\&. It can be updated automatically from the command\-line, and supports the optional submission of updated version data back to the maintainers\&.
.SH "OPTIONS"
.PP
Below are all of the Nikto command line options and explanations\&. A brief version of this text is available by running Nikto with the \-H (\-Help) option\&.
.PP
\fB\-ask\fR \fIyes|no|auto\fR
.RS 4
Whether to ask about submitting updates\&. Options: yes (ask about each), no (don't ask, don't send), auto (don't ask, just send)\&.
.RE
.PP
\fB\-Add\-header\fR \fIheader:value\fR
.RS 4
Add HTTP headers (can be used multiple times, one per header pair)\&.
.RE
.PP
\fB\-check6\fR
.RS 4
Check if IPv6 is working (connects to ipv6\&.google\&.com or value set in nikto\&.conf)\&.
.RE
.PP
\fB\-Cgidirs\fR \fIdirs\fR
.RS 4
Scan these CGI directories\&. Special words "none" or "all" may be used\&. A literal value for a CGI directory such as "/cgi\-test/" may be specified (must include trailing slash)\&.
.RE
.PP
\fB\-config\fR \fIfile\fR
.RS 4
Use this config file instead of the default nikto\&.conf\&.
.RE
.PP
\fB\-dbcheck\fR
.RS 4
Check database and other key files for syntax errors\&.
.RE
.PP
\fB\-Display\fR \fIoptions\fR
.RS 4
Turn on/off display outputs: 1 (Show redirects), 2 (Show cookies received), 3 (Show all 200/OK responses), 4 (Show URLs which require authentication), D (Debug output), E (Display all HTTP errors), P (Print progress to STDOUT), S (Scrub output of IPs and hostnames), V (Verbose output)\&.
.RE
.PP
\fB\-evasion\fR \fItechnique\fR
.RS 4
Encoding technique: 1 (Random URI encoding), 2 (Directory self\-reference), 3 (Premature URL ending), 4 (Prepend long random string), 5 (Fake parameter), 6 (TAB as request spacer), 7 (Change the case of the URL), 8 (Use Windows directory separator), A (Use carriage return as request spacer), B (Use binary value 0x0b as request spacer)\&.
.RE
.PP
\fB\-followredirects\fR
.RS 4
Follow 3xx redirects to new location\&.
.RE
.PP
\fB\-Format\fR \fIformat\fR
.RS 4
Save file format: csv (Comma\-separated\-value), json (JSON Format), htm (HTML Format), nbe (Nessus NBE format), sql (Generic SQL), txt (Plain text), xml (XML Format)\&.
.RE
.PP
\fB\-Help\fR
.RS 4
Display extended help information\&.
.RE
.PP
\fB\-host\fR \fItarget\fR
.RS 4
Host(s) to target\&. Can be an IP address, hostname or text file of hosts\&. A single dash (\-) maybe used for stdout\&. Can also parse nmap \-oG style output\&.
.RE
.PP
\fB\-id\fR \fIid:pass[:realm]\fR
.RS 4
ID and password to use for host Basic host authentication\&. Format is "id:password" or "id:password:realm"\&.
.RE
.PP
\fB\-ipv4\fR
.RS 4
IPv4 Only\&.
.RE
.PP
\fB\-ipv6\fR
.RS 4
IPv6 Only\&.
.RE
.PP
\fB\-key\fR \fIfile\fR
.RS 4
Client certificate key file\&.
.RE
.PP
\fB\-list\-plugins\fR
.RS 4
List all available plugins, perform no testing\&.
.RE
.PP
\fB\-maxtime\fR \fItime\fR
.RS 4
Maximum testing time per host (e\&.g\&., 1h, 60m, 3600s)\&.
.RE
.PP
\fB\-mutate\fR \fIoptions\fR
.RS 4
Guess additional file names: 1 (Test all files with all root directories), 2 (Guess for password file names), 3 (Enumerate user names via Apache), 4 (Enumerate user names via cgiwrap), 5 (Attempt to brute force sub\-domain names), 6 (Attempt to guess directory names from dictionary file)\&.
.RE
.PP
\fB\-mutate\-options\fR \fIoptions\fR
.RS 4
Provide information for mutates\&.
.RE
.PP
\fB\-no404\fR
.RS 4
Disables nikto attempting to guess a 404 page\&.
.RE
.PP
\fB\-nointeractive\fR
.RS 4
Disable interactive features\&.
.RE
.PP
\fB\-nolookup\fR
.RS 4
Do not perform name lookups on IP addresses\&.
.RE
.PP
\fB\-noslash\fR
.RS 4
Strip trailing slash from URL (e\&.g\&., '/admin/' to '/admin')\&.
.RE
.PP
\fB\-nossl\fR
.RS 4
Do not use SSL to connect to the server\&.
.RE
.PP
\fB\-Option\fR \fIname=value\fR
.RS 4
Over\-ride an option in nikto\&.conf, can be issued multiple times\&.
.RE
.PP
\fB\-output\fR \fIfile\fR
.RS 4
Write output to the file specified ('.' for auto\-name)\&. The format used will be taken from the file extension\&. This can be over\-ridden by using the \-Format option\&.
.RE
.PP
\fB\-Pause\fR \fIseconds\fR
.RS 4
Seconds (integer or floating point) to delay between each test\&.
.RE
.PP
\fB\-Plugins\fR \fIlist\fR
.RS 4
List of plugins to run (default: ALL)\&.
.RE
.PP
\fB\-port\fR \fIports\fR
.RS 4
TCP port(s) to target\&. To test more than one port on the same host, specify the list of ports\&. Ports can be specified as a range (i\&.e\&., 80\-90), or as a comma\-delimited list, (i\&.e\&., 80,88,90)\&. If not specified, port 80 is used\&.
.RE
.PP
\fB\-RSAcert\fR \fIfile\fR
.RS 4
Client certificate file\&.
.RE
.PP
\fB\-root\fR \fIpath\fR
.RS 4
Prepend the value specified to the beginning of every request\&. This is useful to test applications or web servers which have all of their files under a certain directory\&.
.RE
.PP
\fB\-Save\fR \fIdirectory\fR
.RS 4
Save positive responses to this directory ('.' for auto\-name)\&.
.RE
.PP
\fB\-ssl\fR
.RS 4
Only test SSL on the ports specified\&. Using this option will dramatically speed up requests to HTTPS ports, since otherwise the HTTP request will have to timeout first\&.
.RE
.PP
\fB\-timeout\fR \fIseconds\fR
.RS 4
Seconds to wait before timing out a request\&. Default timeout is 10 seconds\&.
.RE
.PP
\fB\-Tuning\fR \fIoptions\fR
.RS 4
Tuning options will control the test that Nikto will use against a target\&. By default, if any options are specified, only those tests will be performed\&. If the "x" option is used, it will reverse the logic and exclude only those tests\&. Use the reference number or letter to specify the type, multiple may be used:
.sp
0 \- File Upload
.sp
1 \- Interesting File / Seen in logs
.sp
2 \- Misconfiguration / Default File
.sp
3 \- Information Disclosure
.sp
4 \- Injection (XSS/Script/HTML)
.sp
5 \- Remote File Retrieval \- Inside Web Root
.sp
6 \- Denial of Service
.sp
7 \- Remote File Retrieval \- Server Wide
.sp
8 \- Command Execution / Remote Shell
.sp
9 \- SQL Injection
.sp
a \- Authentication Bypass
.sp
b \- Software Identification
.sp
c \- Remote Source Inclusion
.sp
d \- WebService
.sp
e \- Administrative Console
.sp
x \- Reverse Tuning Options (i\&.e\&., include all except specified)
.RE
.PP
\fB\-until\fR \fItime\fR
.RS 4
Run until the specified time or duration\&.
.RE
.PP
\fB\-url\fR \fItarget\fR
.RS 4
Target host/URL (alias of \-host)\&.
.RE
.PP
\fB\-Userdbs\fR \fItype\fR
.RS 4
Load only user databases, not the standard databases\&. Options: all (Disable standard dbs and load only user dbs), tests (Disable only db_tests and load udb_tests)\&.
.RE
.PP
\fB\-useragent\fR \fIstring\fR
.RS 4
Over\-rides the default useragent\&.
.RE
.PP
\fB\-usecookies\fR
.RS 4
Use cookies from responses in future requests\&.
.RE
.PP
\fB\-useproxy\fR \fIproxy\fR
.RS 4
Use the HTTP proxy defined in the configuration file, or given as argument in the format http://server:port\&.
.RE
.PP
\fB\-Version\fR
.RS 4
Display the Nikto software, plugin and database versions\&.
.RE
.PP
\fB\-vhost\fR \fIhostname\fR
.RS 4
Specify the Host header to be sent to the target\&.
.RE
.PP
\fB\-404code\fR \fIcodes\fR
.RS 4
Ignore these HTTP codes as negative responses (always)\&. Format is "302,301"\&.
.RE
.PP
\fB\-404string\fR \fIstring\fR
.RS 4
Ignore this string in response body content as negative response (always)\&. Can be a regular expression\&.
.RE
.SH "FILES"
.PP
\fInikto\&.conf\fR
.RS 4
The Nikto configuration file\&. This sets Nikto\'s global options\&. Several nikto\&.conf files may exist and are parsed in the below order\&. As each configuration file is loaded is supersedes any previously set configuration:
.sp
.RS 4
\h'-04'\(bu\h'+03'System wide (e\&.g\&. /etc/nikto\&.conf)
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'Home directory (e\&.g\&. $HOME/nikto\&.conf)
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'Current directory (e\&.g\&. \&./nikto\&.conf)
.RE
.RE
.PP
\fI${NIKTO_DIR}/databases/db*\fR
.RS 4
Database files that nikto uses to check for vulnerabilities and issues within the web server\&.
.RE
.PP
\fI${NIKTO_DIR}/plugins/*\&.plugin\fR
.RS 4
All nikto\'s plugins exist here\&. Nikto itself is just a wrapper script to manage CLI and pass through to the plugins\&.
.RE
.PP
\fI${NIKTO_DIR}/templates\fR
.RS 4
Contains the templates for nikto\'s output formats\&.
.RE
.SH "BUGS"
.PP
The current features are not supported:
.sp
.RS 4
\h'-04'\(bu\h'+03'SOCKS Proxies
.RE
.SH "AUTHORS"
.PP
Nikto is written and maintained by Chris Sullo and David Lodge\&. See the main documentation for other contributors\&.
.PP
All code is Copyright CIRT, Inc., except LibWhisker which is Copyright (c) 2009, Jeff Forristal (wiretrip.net)\&.  Other portions of code may be (C) as specified\&.
.SH "SEE ALSO"
.PP

\fINikto Homepage\fR\&[1]
.SH "NOTES"
.IP " 1." 4
Nikto Homepage
.RS 4
\%http://cirt.net/
.RE
